name: Build Minecraft Mod

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build the mod
        run: ./gradlew build

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-mod
          path: build/libs/*.jar
